export type {
  AlertType,
  attributesType,
  ButtonType,
  CheckedType,
  ErrorType,
  FormType,
  ImageType,
  InputType,
  OptionType,
  SelectType,
  TagType,
} from "./src/components";
export type {
  BannerSectionType,
  CarousselSectionType,
  ContactSectionType,
  DevisSectionType,
  EventSectionType,
  FooterType,
  HeaderType,
  HeroConceptSectionType,
  HeroEventSectionType,
  HeroMainSectionType,
  HeroSectionType,
  PageProps,
  PageType,
  RelanceSectionType,
  SectionsType,
  SectionType,
  SeoType,
  SlideSectionType,
} from "./src/sections";
