services:
  - type: web
    name: strapi
    env: node
    plan: free
    buildCommand: cd apps/cms && npm run build-cms
    startCommand: cd apps/cms && npm run start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: API_TOKEN_SALT
        value: IoaF9pWst7KpGWOSfDoGKg
      - key: TRANSFER_TOKEN_SALT
        value: lCrKWbZeHfaEVij5KEpipg
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: false
      - key: DATABASE_URL
        value: postgres://tatiana.nacea:7xiRUphry6Am@ep-purple-mud-218447.eu-central-1.aws.neon.tech/nacea_db?ssl=true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
